version: "3.7"

services:
  nginx:
    build: ./nginx
    ports:
      - ${DEPLOY_PORT}:80
    volumes: 
      - static_volume:/montrek/montrek/baseclasses/static
      - uploads_volume:/montrek/uploads
    depends_on:
      - web
    environment:
      - APP_PORT=${APP_PORT}
    restart: "on-failure"


  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd montrek &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    gunicorn --chdir montrek montrek.wsgi:application --bind 0.0.0.0:${APP_PORT}"
    volumes:
      - .:/montrek
      - static_volume:/montrek/montrek/baseclasses/static
      - uploads_volume:/montrek/uploads
    env_file:
      - .env
    image: montrek_app
    expose:
      - ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: "on-failure"
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd montrek && 
                    celery --app=montrek worker --loglevel=info"
    volumes:
      - .:/montrek
      - static_volume:/montrek/montrek/baseclasses/static
      - uploads_volume:/montrek/uploads
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:7-alpine

  flower:
    build: ./montrek
    command: celery flower -A montrek.celery_app --port=5555 --broker={CELERY_BROKER_URL}
    ports:
      - 5555:5555
    env_file:
      - .env
    depends_on:
      - redis
      - celery

volumes:
  db_data:
  static_volume:
  uploads_volume:
