services:
  nginx:
    build: ./nginx
    ports:
      - ${DEPLOY_PORT}:80
    volumes: 
      - static_volume:/montrek/montrek/baseclasses/static
      - uploads_volume:/montrek/uploads
    depends_on:
      - web
    environment:
      - APP_PORT=${APP_PORT}
      - PROJECT_NAME=${PROJECT_NAME}
    restart: "on-failure"
    networks:
      - montrek_network


  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd montrek &&
                    python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    gunicorn --chdir montrek montrek.wsgi:application --bind 0.0.0.0:${APP_PORT}"
    volumes:
      - .:/montrek
      - static_volume:/montrek/montrek/baseclasses/static
      - uploads_volume:/montrek/uploads
    env_file:
      - .env
    image: montrek_app
    expose:
      - ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: "on-failure"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=${DEPLOY_HOST}
    networks:
      - montrek_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - montrek_network
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd montrek && 
                    celery --app=montrek worker --loglevel=info"
    volumes:
      - .:/montrek
      - static_volume:/montrek/montrek/baseclasses/static
      - uploads_volume:/montrek/uploads
    env_file:
      - .env
    depends_on:
      - web
      - db
      - redis
    networks:
      - montrek_network

  redis:
    image: redis:7-alpine
    networks:
      - montrek_network

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery flower -A montrek.celery_app --port=${FLOWER_PORT} --broker={CELERY_BROKER_URL}
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - celery
    networks:
      - montrek_network

volumes:
  db_data:
  static_volume:
  uploads_volume:

networks:
  montrek_network:
    driver: bridge
