include:
  - db_yml/${DB_ENGINE}.yml
services:
  nginx:
    build: ./nginx
    ports:
      - ${DEPLOY_PORT}:${DEPLOY_PORT}
    volumes:
      - static_volume:/montrek/static
      - uploads_volume:/montrek/uploads
    depends_on:
      - web
    environment:
      - APP_PORT=${APP_PORT}
      - DEPLOY_PORT=${DEPLOY_PORT}
      - DEPLOY_HOST=${DEPLOY_HOST}
      - PROJECT_NAME=${PROJECT_NAME}
      - ENABLE_KEYCLOAK=${ENABLE_KEYCLOAK}
      - KEYCLOAK_PORT=${KEYCLOAK_PORT}
      - FLOWER_PORT=${FLOWER_PORT}
    restart: "on-failure"
    networks:
      - montrek_network

  web:
    image: ghcr.io/montrek-software/montrek-container:latest
    user: "0:0"
    environment:
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - SERVICE=web
      - PIUD=${USER_ID}
      - PGUD=${GROUP_ID}
    volumes:
      - .:/montrek
      - static_volume:/montrek/static
      - uploads_volume:/montrek/uploads
    env_file:
      - .env
    expose:
      - ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
      - redis
    networks:
      - montrek_network

  sequential_worker:
    image: ghcr.io/montrek-software/montrek-container:latest
    user: "0:0"
    environment:
      - SERVICE=sequential_worker
      - PIUD=${USER_ID}
      - PGUD=${GROUP_ID}
    volumes:
      - .:/montrek
      - static_volume:/montrek/static
      - uploads_volume:/montrek/uploads
    env_file:
      - .env
    depends_on:
      - web
      - db
      - redis
    networks:
      - montrek_network

  parallel_worker:
    image: ghcr.io/montrek-software/montrek-container:latest
    user: "0:0"
    environment:
      - SERVICE=parallel_worker
      - PIUD=${USER_ID}
      - PGUD=${GROUP_ID}
    volumes:
      - .:/montrek
      - static_volume:/montrek/static
      - uploads_volume:/montrek/uploads
    env_file:
      - .env
    depends_on:
      - web
      - db
      - redis
    networks:
      - montrek_network

  celery_beat:
    image: ghcr.io/montrek-software/montrek-container:latest
    user: "0:0"
    environment:
      - SERVICE=celery_beat
      - PIUD=${USER_ID}
      - PGUD=${GROUP_ID}
    volumes:
      - .:/montrek
    env_file:
      - .env
    depends_on:
      - web
      - db
      - redis
      - parallel_worker
      - sequential_worker
    networks:
      - montrek_network

  redis:
    image: redis:7-alpine
    networks:
      - montrek_network

  flower:
    image: mher/flower:2.0.1
    command: celery flower -A montrek.celery_app --port=${FLOWER_PORT} --broker={CELERY_BROKER_URL} --basic_auth=admin:${ADMIN_PASSWORD}
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - sequential_worker
      - parallel_worker
    networks:
      - montrek_network

  keycloak-db:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - montrek_network
    profiles:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_PROXY: edge
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: auth.${PROJECT_NAME}.${DEPLOY_HOST}
      KC_HOSTNAME_STRICT: false
    depends_on:
      - keycloak-db
    networks:
      - montrek_network
    profiles:
      - keycloak

volumes:
  db_data:
  static_volume:
  uploads_volume:
  keycloak_db_data:

networks:
  montrek_network:
    driver: bridge
