include:
  - db_yml/${DB_ENGINE}.yml
services:
  nginx:
    build: ./nginx
    ports:
      - ${DEPLOY_PORT}:${DEPLOY_PORT}
    volumes:
      - static_volume:/montrek/static
      - uploads_volume:/montrek/uploads
    depends_on:
      - web
    environment:
      - APP_PORT=${APP_PORT}
      - DEPLOY_PORT=${DEPLOY_PORT}
      - PROJECT_NAME=${PROJECT_NAME}
    restart: "on-failure"
    networks:
      - montrek_network

  web:
    image: montrek_app
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd montrek &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --chdir montrek montrek.wsgi:application --bind 0.0.0.0:${APP_PORT} --timeout 300"
    volumes:
      - .:/montrek
      - static_volume:/montrek/static
      - uploads_volume:/montrek/uploads
    env_file:
      - .env
    expose:
      - ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: "on-failure"
    depends_on:
      - db
      - redis
    networks:
      - montrek_network

  sequential_worker:
    image: montrek_app
    command: sh -c "cd montrek && celery --app=montrek worker --loglevel=info -Q sequential_queue --concurrency=1" -n sequential_worker@%h
    volumes:
      - .:/montrek
      - static_volume:/montrek/static
      - uploads_volume:/montrek/uploads
    env_file:
      - .env
    depends_on:
      - web
      - db
      - redis
    networks:
      - montrek_network

  parallel_worker:
    image: montrek_app
    command: sh -c "cd montrek && celery --app=montrek worker --loglevel=info -Q parallel_queue --concurrency=4" -n parallel_worker@%h
    volumes:
      - .:/montrek
      - static_volume:/montrek/static
      - uploads_volume:/montrek/uploads
    env_file:
      - .env
    depends_on:
      - web
      - db
      - redis
    networks:
      - montrek_network

  celery_beat:
    image: montrek_app
    command: sh -c "cd montrek && celery --app=montrek beat --loglevel=info"
    volumes:
      - .:/montrek
    env_file:
      - .env
    depends_on:
      - web
      - db
      - redis
      - parallel_worker
      - sequential_worker
    networks:
      - montrek_network

  redis:
    image: redis:7-alpine
    networks:
      - montrek_network

  flower:
    image: mher/flower:2.0.1
    command: celery flower -A montrek.celery_app --port=${FLOWER_PORT} --broker={CELERY_BROKER_URL}
    ports:
      - ${FLOWER_PORT}:${FLOWER_PORT}
    env_file:
      - .env
    depends_on:
      - web
      - redis
      - sequential_worker
      - parallel_worker
    networks:
      - montrek_network

  keycloak-db:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - montrek_network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    networks:
      - montrek_network
volumes:
  db_data:
  static_volume:
  uploads_volume:
  keycloak_db_data:

networks:
  montrek_network:
    driver: bridge
