version: "3.7"

services:
  nginx:
    build: ./nginx
    ports:
      - ${DEPLOY_PORT}:80
    volumes: 
      - static_volume:/home/app/montrek/montrek/baseclasses/static
    depends_on:
      - web
    environment:
      - APP_PORT=${APP_PORT}
    restart: "on-failure"


  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd montrek &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py collectstatic --noinput &&
                    gunicorn --chdir montrek montrek.wsgi:application --bind 0.0.0.0:${APP_PORT}"
    volumes:
      - .:/montrek
      - static_volume:/home/app/montrek/montrek/baseclasses/static
    env_file:
      - .env
    image: montrek_app
    expose:
      - ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: "on-failure"
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - db_data:${DB_VOLUME}

volumes:
  db_data:
  static_volume:
