name: Release Drafter

on:
  push:
    branches:
      - main # <- change if your default branch is different
    tags:
      - "v*" # when you push a tag like v1.2.3 we'll publish
  pull_request_target:
    types: [opened, reopened, synchronize, edited, labeled, unlabeled]
  workflow_dispatch:

permissions:
  contents: write # needed to update/publish releases
  pull-requests: write # needed for autolabeler

jobs:
  update_release_draft:
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Update draft release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Publish the draft as a release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  autolabeler:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label PRs (no release update)
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
          disable-releaser: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
